version: '3.8'
services:
  payment-service:
    build: .
    ports:
      - "3000:3000"
      - "50051:50051"
      - "9091:9091"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/payment_service
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379/0
      - JAEGER_HOST=jaeger
      - LOKI_URL=http://loki:3100
      - JWT_SECRET=your-secret-key
      - STRIPE_API_KEY=your-stripe-key
      - PAYPAL_CLIENT_ID=your-paypal-client-id
      - PAYPAL_SECRET=your-paypal-secret
    depends_on:
      - db
      - kafka
      - redis
      - jaeger
      - loki

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_service
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  db-data: